---
- name: Add ppa Repository
  become: yes
  apt_repository: repo=ppa:ondrej/php state=present

- name: Update apt
  become: yes
  apt: update_cache=yes

- name: Install php7.0
  become: yes
  apt: pkg=php7.0 state=latest

- name: Install php7.0-fpm
  become: yes
  apt: pkg=php7.0-fpm state=latest

- name: Install PHP Packages
  become: yes
  apt: pkg={{ item }} state=latest
  with_items: "{{php.packages}}"
  when: php.packages is defined

- include: configure.yml